function T = build_grid_summary_table(grid)
% BUILD_GRID_SUMMARY_TABLE  Tabla maestra en formato largo: una fila por
% cada combinacion (delta, eta) de la malla, con todas las metricas de
% la Seccion 19 de la propuesta como columnas (crecimiento, perdidas
% -incluyendo varianza y CVaR-, costos, concentracion, supervivencia).
%
% A diferencia de los heatmaps (que muestran UNA metrica a la vez sobre
% la malla completa), esta tabla deja las 19+ metricas de cada ejecucion
% juntas para poder cruzarlas libremente (ordenar, filtrar, graficar
% cualquier par de columnas) sin que el codigo preseleccione un "ganador".
%
% ENTRADA
%   grid : struct de run_grid_delta_eta_wdro_only.m
%
% SALIDA
%   T : table de MATLAB, una fila por combinacion (delta, eta) resuelta
%       (las combinaciones que fallaron por completo -- results_wdro
%       vacio -- se omiten, no se rellenan con NaN silenciosamente).

    nd = numel(grid.delta_grid);
    ne = numel(grid.eta_grid);
    alpha = grid.alpha;

    rows = {};
    for i = 1:nd
        for j = 1:ne
            r = grid.results_wdro{i, j};
            if isempty(r)
                continue
            end
            m = compute_metrics(r, alpha);

            is_baseline = ~isempty(grid.baseline_col) && (j == grid.baseline_col);

            row = table( ...
                grid.delta_grid(i), grid.eta_grid(j), is_baseline, ...
                m.wealth_final, m.log_growth_mean, m.CAGR, ...
                m.variance_monthly, m.max_drawdown, m.worst_month, ...
                m.var5_monthly, m.VaR_loss, m.CVaR_loss, ...
                m.turnover_total, m.cost_total, m.cost_mean, ...
                m.max_weight_mean, m.max_weight_max, m.Neff_mean, ...
                m.n_violations_delta, m.min_growth_real, ...
                grid.feas_wdro(i, j), m.n_solver_failed, m.n_months, ...
                grid.CAGR_diff(i, j), grid.MDD_diff(i, j), ...
                'VariableNames', { ...
                    'delta', 'eta', 'es_baseline', ...
                    'riqueza_final', 'log_crecimiento_medio', 'CAGR', ...
                    'varianza_mensual', 'max_drawdown', 'peor_mes', ...
                    'percentil5_mensual', 'VaR_perdida', 'CVaR_perdida', ...
                    'turnover_total', 'costo_total', 'costo_medio', ...
                    'peso_max_promedio', 'peso_max_pico', 'Neff_promedio', ...
                    'violaciones_delta', 'min_factor_crecimiento', ...
                    'fraccion_factible', 'fallos_solver', 'n_meses', ...
                    'CAGR_diff_vs_baseline', 'MDD_diff_vs_baseline'} ...
            );
            rows{end + 1} = row; %#ok<AGROW>
        end
    end

    if isempty(rows)
        error('build_grid_summary_table:empty', ...
            'Ninguna combinacion de la malla tiene resultados guardados.');
    end

    T = vertcat(rows{:});
    T = sortrows(T, {'delta', 'eta'});
end
